Updated foundation, ADD: installer test

diff --git a/.github/workflows/test_macos.yml b/.github/workflows/test_macos.yml
--- a/.github/workflows/test_macos.yml
+++ b/.github/workflows/test_macos.yml
@@ -50,18 +50,90 @@ jobs:
           edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
           edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
           edamame_id: ${{ github.run_id }}
+          auto_remediate: true
+          network_scan: true
           checkout: true
-          
+
       - name: Install additional packages w/ Homebrew
         run: |
           brew install protobuf
           brew install wget
+
+      - name: Setup signing
+        shell: bash
+        run: |
+          # Create certificate files from secrets base64
+          echo ${{ secrets.APPLE_DEVELOPMENT_CER }} | base64 --decode > certificate_dev.cer
+          echo ${{ secrets.APPLE_DEVELOPMENT_KEY }} | base64 --decode > certificate_dev.key
+          echo ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER_CER }} | base64 --decode > certificate_installer.cer
+          echo ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER_KEY }} | base64 --decode > certificate_installer.key
+          echo ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION_CER }} | base64 --decode > certificate_application.cer
+          echo ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION_KEY }} | base64 --decode > certificate_application.key
+          
+          # Create p12 file
+          openssl pkcs12 -export -name zup -in certificate_dev.cer -inkey certificate_dev.key -passin pass:${{ secrets.APPLE_P12_PASSWORD }} -out certificate_dev.p12 -passout pass:${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
+          openssl pkcs12 -export -name zup -in certificate_installer.cer -inkey certificate_installer.key -passin pass:${{ secrets.APPLE_P12_PASSWORD }} -out certificate_installer.p12 -passout pass:${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
+          openssl pkcs12 -export -name zup -in certificate_application.cer -inkey certificate_application.key -passin pass:${{ secrets.APPLE_P12_PASSWORD }} -out certificate_application.p12 -passout pass:${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
+          
+          # Configure Keychain
+          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+          security create-keychain -p "${{ secrets.MACOS_KEYCHAIN_PASSWORD }}" $KEYCHAIN_PATH
+          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+          security unlock-keychain -p "${{ secrets.MACOS_KEYCHAIN_PASSWORD }}" $KEYCHAIN_PATH
+          
+          # Import certificates on Keychain
+          security import certificate_dev.p12 -P "${{ secrets.APPLE_P12_PASSWORD }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+          security import certificate_installer.p12 -P "${{ secrets.APPLE_P12_PASSWORD }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+          security import certificate_application.p12 -P "${{ secrets.APPLE_P12_PASSWORD }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+
+          # Verify Keychain
+          security list-keychain -d user -s $KEYCHAIN_PATH
+
+          # Store notarization credentials
+          echo ${{ secrets.APPLE_APPSTORE_CONNECT_API_KEY }} | base64 --decode > appstore_connect_api_key.p8
+          xcrun notarytool store-credentials -k appstore_connect_api_key.p8 -d ${{ secrets.APPLE_APPSTORE_CONNECT_API_KEY_ID }} -i ${{ secrets.APPLE_APPSTORE_CONNECT_API_ISSUER_ID }} Edamame
+
+      - name: Build helper and its standalone installer
+        shell: bash
+        run: |
+          rustup target add x86_64-apple-darwin
+          rustup target add aarch64-apple-darwin
+          cargo build --release --target x86_64-apple-darwin
+          cargo build --release --target aarch64-apple-darwin
+          mkdir -p target/release
+          lipo -create -output target/release/edamame_helper \
+            target/x86_64-apple-darwin/release/edamame_helper \
+            target/aarch64-apple-darwin/release/edamame_helper
+
+      - name: Packaging and signing of the Helper
+        shell: bash
+        run: |
+          VERSION=$(grep '^version =' ./Cargo.toml | awk '{print $3}' | tr -d '"')
+          ./macos/make-pkg.sh && ./macos/make-distribution-pkg.sh
+          # Final naming with version
+          cp ./target/pkg/edamame-helper.pkg ./target/pkg/edamame-helper-macos-${VERSION}.pkg
+
+      - name: Notarization
+        shell: bash
+        run: |          
+          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+          ./macos/notarization.sh ./target/pkg/edamame-helper.pkg
 
       - name: Tests
         id: tests
         shell: bash
         run: |
           make test
+          # Test the installer
+          sudo installer -verboseR -pkg ./target/pkg/edamame-helper-macos-${VERSION}.pkg -target /
+          # Test if the helper is running
+          sleep 20
+          if [ -f /var/log/edamame_helper.log ]; then
+            cat /var/log/edamame_helper.log
+          else
+            echo "Helper log file not found"
+            exit 1
+          fi
         continue-on-error: true
 
       - name: Slack alerts
diff --git a/.github/workflows/test_windows.yml b/.github/workflows/test_windows.yml
--- a/.github/workflows/test_windows.yml
+++ b/.github/workflows/test_windows.yml
@@ -51,6 +51,8 @@ jobs:
           edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
           edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
           edamame_id: ${{ github.run_id }}
+          auto_remediate: true
+          network_scan: true
           checkout: true
 
       - name: Install additional packages w/ Chocolatey
@@ -58,11 +60,47 @@ jobs:
           choco install protoc wget
           dotnet tool install --global AzureSignTool
 
+      - name: Setup for edamame_helper
+        shell: bash
+        run: |
+          cargo install cargo-wix
+          choco install wixtoolset
+          echo "/c/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/10.0.19041.0/x64" >> $GITHUB_PATH
+
+      - name: Build helper and its standalone installer
+        shell: bash
+        run: | 
+          cargo build --release
+          cargo wix --nocapture --no-build
+
+      - name: Signing of the Helper
+        # We can't use bash here, as the AzureSignTool is a .NET tool
+        run: |
+          $VERSION = (Get-Content ./Cargo.toml | Select-String '^version =' | ForEach-Object { $_.Line.Split('=')[1].Trim().Trim('"') })
+          AzureSignTool sign -kvt ${{ secrets.AZURE_SIGN_TENANT_ID }} -kvu ${{ secrets.AZURE_SIGN_KEY_VAULT_URI }} -kvi ${{ secrets.AZURE_SIGN_CLIENT_ID }} -kvs ${{ secrets.AZURE_SIGN_CLIENT_SECRET }} -kvc ${{ secrets.AZURE_SIGN_CERT_NAME }} -tr http://timestamp.digicert.com -v ./target/wix/edamame_helper-$VERSION-x86_64.msi
+
+      - name: Naming of the Helper
+        shell: bash
+        run: |
+          VERSION=$(grep '^version =' ./Cargo.toml | awk '{print $3}' | tr -d '"')
+          # Final naming with version, with the hope of future universal arm/x86 packages like with macOS...
+          cp ./target/wix/edamame_helper-${VERSION}-x86_64.msi ./target/wix/edamame-helper-windows-${VERSION}.msi
+
       - name: Tests
         id: tests
         shell: bash
         run: |
           make test
+          # Test the installer
+          msiexec.exe -i ./target/wix/edamame-helper-windows-${VERSION}.msi -qn
+          sleep 20
+          year=$(date +%Y)
+          if [ -f "/c/Program Files/edamame_helper/bin/edamame_helper.${year}*" ]; then
+            cat "/c/Program Files/edamame_helper/bin/edamame_helper.${year}*"
+          else
+            echo "Helper log file not found"
+            exit 1
+          fi
         continue-on-error: true
 
       - name: Slack alerts
